version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/recipedb
    volumes:
      - ./app:/app/app  # Mount local 'app' folder for live reloading
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata:
  # ollama_data:
