"""Add cascade delete to meal_plans.recipe_id

Revision ID: d89bba626906
Revises: 28f954b854a7
Create Date: 2025-05-14 09:40:46.171522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89bba626906'
down_revision: Union[str, None] = '28f954b854a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meal_plans_recipe_id_fkey', 'meal_plans', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plans', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.create_foreign_key('meal_plans_recipe_id_fkey', 'meal_plans', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
